# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: ci

on:
  push:
  pull_request:

env:
  USE_BSPM: "true"
  _R_CHECK_FORCE_SUGGESTS_: "false"

jobs:
  ci:
    strategy:
      matrix:
        include:
          - {os: macOS-latest}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Bootstrap
        working-directory: survlearners
        run: |
          curl -OLs https://eddelbuettel.github.io/r-ci/run.sh
          chmod 0755 run.sh
          ./run.sh bootstrap

      - name: Dependencies
        working-directory: survlearners
        run: ./run.sh install_all

      - name: Test
        working-directory: survlearners
        run: ./run.sh run_tests

      - name: Print logs
        if: failure()
        working-directory: survlearners
        run: ./run.sh dump_logs_by_extension "fail"
