# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: ci

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  ci:
    runs-on: macOS-latest
    env:
      USE_BSPM: "true"
      _R_CHECK_FORCE_SUGGESTS_: "false"
      GITHUB_PAT: ${{ secrets.SURVLEARNER_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@v1 # For pkgdown page

      - name: Setup R
        working-directory: r-package/survlearners
        run: |
          curl -OLs https://eddelbuettel.github.io/r-ci/run.sh
          chmod 0755 run.sh
          ./run.sh bootstrap

      - name: Install dependencies
        working-directory: r-package/survlearners
        run: |
          ./run.sh install_all
          # Install OSX deps manually
          sudo Rscript -e "install.packages(c('survival', 'glmnet', 'grf'))"

      - name: Test
        working-directory: r-package/survlearners
        run: |
          ./run.sh run_tests
          # Treat WARNING and NOTE as error
          if ./run.sh dump_logs_by_extension "00check.log" | grep 'WARNING\|NOTE'; then
            echo "Found warnings/notes, treating as errors."
            exit 1
          fi

      - name: Print logs
        if: failure()
        working-directory: r-package/survlearners
        run: ./run.sh dump_logs

      - name: Build pkgdown
        working-directory: r-package/survlearners
        run: |
          sudo Rscript -e "install.packages('pkgdown')"
          sudo Rscript -e "install.packages(c('ggplot2', 'rmarkdown'))"
          cp ../../README.md .
          Rscript -e "pkgdown::build_site()"

      - name: Deploy to GitHub pages
        if: github.ref == 'refs/heads/master'
        working-directory: r-package/survlearners
        run: |
          git config --local user.name "GITHUB_ACTIONS"
          git config --local user.email "GITHUB_ACTIONS@users.noreply.github.com"
          mv docs/ ../../docs
          git add --force ../../docs/
          git commit --allow-empty -m "Update gh-pages"
          git push --force https://$(GITHUB_PAT)@github.com/som-shahlab/survlearners.git HEAD:gh-pages
